INSERT INTO gfdvoc (cod, description) VALUES ('1. ', 'РАЗДЕЛ: ИЗУЧЕНИЕ ИСПОЛЬЗОВАНИЯ И СОСТОЯНИЯ ЗЕМЕЛЬ ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1. ', 'Подраздел: Геодезические и картографические работы ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1. ', 'Геодезические работы специального назначения ');
INSERT INTO gfdvoc (cod, description) VALUES (' 1-1-1-1.  ', ' Технические проекты на выполнение геодезических работ по созданию и развитию опорных межевых сетей  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-2. ', 'Каталоги и списки координат и высот пунктов опорных межевых сетей со схемами расположения пунктов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-3. ', 'Технические отчеты о создании и развитии опорных межевых сетей ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-4. ', 'Материалы вычислений,  перевычислений и установления параметров связи геодезических систем координат ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-5. ', 'Иные материалы по созданию и развитию опорных межевых сетей ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-6. ', 'Инженерно-геодезические изыскания. Технические проекты проведения работ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-7. ', 'Инженерно-геодезические изыскания. Каталоги и списки координат и высот пунктов со схемами расположения пунктов  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-8. ', 'Инженерно-геодезические изыскания. Карты (планы) ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-9. ', 'Инженерно-геодезические изыскания. Технические отчеты о выполненных работах ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-10. ', 'Инженерно-геодезические изыскания. Иные материалы ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-11. ', 'Топографо-геодезические работы. Технические проекты проведения работ  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-12. ', 'Топографо-геодезические работы. Каталоги и списки координат и высот пунктов со схемами расположения пунктов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-13. ', 'Топографо-геодезические работы. Карты (планы) ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-14. ', 'Топографо-геодезические работы. Технические отчеты о выполненных работах ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-1-15. ', 'Топографо-геодезические работы. Иные материалы ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2. ', 'Аэрофототопографические работы специального назначения ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-1. ', 'Технические проекты на выполнение аэросъемочных работ ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-2. ', 'Материалы залетов аэросъемочных работ ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-3. ', 'Аэроснимки, репродукции накидного монтажа ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-4. ', 'Технические отчеты о выполненных аэросъемочных работах ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-5. ', 'Технические отчеты по планово-высотной привязке аэроснимков ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-6. ', 'Материалы фотограмметрической обработки ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-7. ', 'Каталоги и списки координат и высот пунктов, использованных в ходе проведения фотограмметрических работ со снимками  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-8. ', 'Фотопланы (ортофотопланы) на населенные пункты ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-9. ', 'Фотопланы (ортофотопланы) на межселенную территорию ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-10. ', 'Технические отчеты по фотограмметрическим работам ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-2-11. ', 'Иные материалы ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3. ', 'Работы по созданию картографической продукции специального назначения по материалам космической съемки ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-1. ', 'Технические проекты производства работ ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-2. ', 'Необработанные результаты космической съемки ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-3. ', 'Технические отчеты по планово-высотной привязке ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-4. ', 'Материалы фотограмметрической обработки ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-5. ', 'Каталоги и списки координат и высот пунктов, использованных в ходе проведения фотограмметрических работ со снимками ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-6. ', 'Фотопланы (ортофотопланы) на населенные пункты ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-7. ', 'Фотопланы (ортофотопланы) на межселенную территорию ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-8. ', 'Технические отчеты по фотограмметрическим работам ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-3-9. ', 'Иные материалы ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4. ', 'Картографические работы специального назначения ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-1. ', 'Проекты создания карт и редакционные документы на карты и атласы, решения редакционных коллегий или советов, заключения и рецензии и другие документы по вопросам их создания или обновления ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-2. ', 'Составительские оригиналы карт  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-3. ', 'Издательские оригиналы карт ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-4. ', 'Тиражные оттиски карт ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-5. ', 'Составительские оригиналы карт атласов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-6. ', 'Издательские оригиналы карт атласов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-7. ', 'Тиражные оттиски карт атласов и переплетенные экземпляры атласов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-4-8. ', 'Иные материалы ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-5. ', 'Иные материалы геодезических и картографических работ специального назначения ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-1-5-1. ', 'Материалы геодезических работ специального назначения, не вошедшие в статьи 1-1-1 ÷ 1-1-4 данного подраздела ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2.  ', 'Подраздел: Специальные обследования и изыскания ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1. ', 'Материалы специальных обследований и изысканий состояния земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1-1. ', 'Материалы крупномасштабных почвенных обследований ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1-2. ', 'Материалы специальных обследований и изысканий  по выявлению негативных процессов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1-3. ', 'Материалы геоботанических обследований природных кормовых угодий ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1-4. ', 'Материалы геоботанических обследований оленьих пастбищ ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1-5. ', 'Материалы наблюдений и обследований за состоянием земель на специальных полигонах ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-1-6. ', 'Материалы иных специальных обследований и изысканий состояния земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-2. ', 'Материалы специальных обследований и изысканий использования земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-2-1. ', 'Материалы инвентаризации земель по категориям земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-2-2. ', 'Материалы инвентаризации земель по отдельным видам использования (сельскохозяйственные угодья, мелиорированные земли, лесополосы, дороги, нарушенные земли и т.п.) ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-2-3. ', 'Материалы по выявлению неиспользуемых земель или используемых не по целевому назначению ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-2-4. ', 'Материалы наблюдений и обследований за использованием земель на специальных полигонах ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-2-5. ', 'Материалы иных специальных обследований и изысканий использования земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-3. ', 'Материалы вычисления площадей по видам использования и состояния земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-3-1. ', 'Материалы по вычислению площадей сельскохозяйственных угодий и иных земель  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-3-2. ', 'Материалы по вычислению площадей почвенных разностей ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-3-3. ', 'Материалы по вычислению площадей геоботанических контуров ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-3-4. ', 'Материалы вычисления площадей сельскохозяйственных угодий и иных земель по уклонам ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-3-5. ', 'Иные материалы вычисления площадей ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-4. ', 'Иные материалы специальных обследований и изысканий  ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-2-4-1. ', 'Материалы специальных обследований и изысканий, не вошедшие в статьи 1-2-1 ÷ 1-2-3 данного подраздела ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3.  ', 'Подраздел: Оценка качества земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-1. ', 'Материалы оценки качества земель как средства производства в сельском хозяйстве ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-1-1. ', 'Материалы бонитировки почв ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-1-2. ', 'Материалы экономической оценки сельскохозяйственных  угодий ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-1-3. ', 'Материалы внутрихозяйственной оценки земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-1-4. ', 'Материалы по оценке качества и классификации земель по их пригодности для использования в сельском хозяйстве ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-1-5. ', 'Иные материалы по оценке качества земель как средства производства в сельском хозяйстве ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-2. ', 'Материалы оценки продуктивности оленьих пастбищ и наличия биологических ресурсов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-2-1. ', 'Материалы ресурсной оценки оленьих пастбищ ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-2-2. ', 'Материалы эколого-хозяйственной классификации земель, являющихся исконной средой обитания коренных малочисленных народов Севера, Сибири и Дальнего Востока Российской Федерации ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-2-3. ', 'Иные материалы оценки продуктивности оленьих пастбищ и наличия биологических ресурсов ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-3. ', 'Иные материалы оценки качества земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('1-3-3-1. ', 'Материалы оценки качества земель, не вошедшие в статьи 1-3-1 ÷ 1-3-2 данного подраздела ');
INSERT INTO gfdvoc (cod, description) VALUES ('2.  ', 'РАЗДЕЛ: ПЛАНИРОВАНИЕ И ОРГАНИЗАЦИЯ РАЦИОНАЛЬНОГО ИСПОЛЬЗОВАНИЯ ЗЕМЕЛЬ И ИХ ОХРАНЫ ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1.  ', 'Подраздел: Схемы землеустройства использования и охраны земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-1. ', 'Схемы землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-1-1. ', 'Материалы генеральной схемы землеустройства Российской Федерации ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-1-2. ', 'Материалы схем землеустройства территорий субъектов Российской Федерации, муниципальных образований и других административно-территориальных образований ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-2. ', 'Схемы использования и охраны земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-2-1. ', 'Материалы схем использования и охраны земель территорий субъектов Российской Федерации, муниципальных образований и других административно- территориальных образований ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-3. ', 'Иные материалы планирования и организации рационального использования земель и их охраны ');
INSERT INTO gfdvoc (cod, description) VALUES ('2-1-3-1. ', 'Материалы планирования и организации рационального использования земель и их охраны, не вошедшие в статьи 2-1-1 ÷ 2-1-2 данного подраздела ');
INSERT INTO gfdvoc (cod, description) VALUES ('3. ', 'РАЗДЕЛ: ТЕРРИТОРИАЛЬНОЕ ЗЕМЛЕУСТРОЙСТВО ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1.  ', 'Подраздел: Образование новых и упорядочение существующих объектов землеустройства и установление их границ на местности ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1. ', 'Проекты территориального землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1-1. ', 'Материалы проектов границ земельных участков ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1-2. ', 'Материалы проектов перераспределения земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1-3. ', 'Материалы проектов границ муниципальных и других административно-территориальных образований ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1-4. ', 'Материалы проектов границ территориальных зон (охранных, санитарно-защитных и иных зон, ограничивающих использование земельных участков)  ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1-5. ', 'Материалы проектов границ сервитутов ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-1-6. ', 'Иные материалы по проектам территориального землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2. ', 'Установление границ объектов землеустройства на местности ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-1. ', 'Материалы межевания земельных участков ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-2. ', 'Материалы межевания границ муниципальных и других административно-территориальных образований ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-3. ', 'Материалы по установлению черты городских и сельских поселений на местности ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-4. ', 'Карты (планы) земельных участков ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-5. ', 'Карты (планы) границ  муниципальных и других административно-территориальных образований ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-6. ', 'Карты (планы) черты городских и сельских поселений ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-7. ', 'Карты (планы) границ иных объектов землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-2-8. ', 'Иные материалы установления границ объектов землеустройства на местности ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-3. ', 'Иные материалы территориального землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('3-1-3-1. ', 'Материалы территориального землеустройства, не вошедшие в статьи 3-1-1 ÷ 3-1-2 данного подраздела ');
INSERT INTO gfdvoc (cod, description) VALUES ('4.  ', 'РАЗДЕЛ: ВНУТРИХОЗЯЙСТВЕННОЕ ЗЕМЛЕУСТРОЙСТВО ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-1.  ', 'Подраздел: Организация рационального использования земельных участков для осуществления сельскохозяйственного производства ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-1-1. ', 'Проекты внутрихозяйственного землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-1-1-1. ', 'Материалы проектов внутрихозяйственного землеустройства сельскохозяйственных организаций и фермерских хозяйств ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-1-1-2. ', 'Материалы проектов организации территорий отгонных пастбищ  ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-1-1-3. ', 'Материалы проектов организации территории оленьих пастбищ и охотничьих угодий ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-1-1-4. ', 'Иные материалы по проектам внутрихозяйственного землеустройства ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2. ', 'Подраздел: Рабочие проекты ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-1. ', 'Проекты рекультивации земель и защиты от негативного воздействия ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-1-1. ', 'Материалы проектов освоения земель в сельскохозяйственные угодья ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-1-2. ', 'Материалы проектов улучшения сельскохозяйственных угодий ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-2. ', 'Проекты рекультивации земель и защиты от негативного воздействия ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-2-1. ', 'Материалы проектов рекультивации нарушенных земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-2-2. ', 'Материалы проектов консервации земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-2-3. ', 'Материалы проектов защиты земель от негативного воздействия ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-3. ', 'Иные материалы по рабочим проектам ');
INSERT INTO gfdvoc (cod, description) VALUES ('4-2-3-1. ', 'Материалы рабочего проектирования, не вошедшие в статьи 4-2-1 ÷ 4-2-2 данного подраздела ');
INSERT INTO gfdvoc (cod, description) VALUES ('5. ', 'РАЗДЕЛ: АНАЛИЗ И ПРОГНОЗ СОСТОЯНИЯ И ИСПОЛЬЗОВАНИЯ ЗЕМЕЛЬ ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-1. ', 'Подраздел: Анализ использования и состояния земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-1-1. ', 'Аналитические материалы о состоянии и использовании земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-1-1-1. ', 'Отчеты и доклады об использовании и состоянии земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-1-1-2. ', 'Аналитические материалы по использованию земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-1-1-3. ', 'Аналитические материалы по состоянию земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-2. ', 'Подраздел: Прогноз состояния и использования земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-2-1. ', 'Оценка состояния и использования земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-2-1-1. ', 'Материалы прогноза в изменении использования и состояния земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-2-1-2. ', 'Рекомендации по предупреждению и устранению негативных явлений ');
INSERT INTO gfdvoc (cod, description) VALUES ('5-2-1-3. ', 'Иные материалы по оценке состояния использования земель ');
INSERT INTO gfdvoc (cod, description) VALUES ('6. ', 'РАЗДЕЛ: ИНЫЕ МАТЕРИАЛЫ И ДОКУМЕНТЫ, НАХОДЯЩИЕСЯ В ГОСУДАРСТВЕННОМ ФОНДЕ ДАННЫХ ');
